# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindusertohost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumpserver.Host'),
        ),
    ]
