# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0003_auto_20161214_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='last_login',
        ),
        migrations.AddField(
            model_name='log',
            name='build_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
