# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0004_auto_20161214_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_tiime_path',
            new_name='log_time_path',
        ),
    ]
