# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpserver', '0005_auto_20161215_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumpserver.Auth_user'),
        ),
    ]
